// Fleet360 - Comprehensive Realistic Mock Data Layer

export const mockDashboardSummary = {
  active_vehicles: 247,
  total_vehicles: 280,
  active_vehicles_pct: 88.2,
  critical_alerts: 5,
  today_revenue: 24285000, // ₹2.43 Cr
  revenue_trend_pct: 2.4,
  fleet_utilization_pct: 94.2,
  utilization_trend_pct: 2.1,
  routes_on_schedule: 432,
  routes_total: 440,
  routes_on_schedule_pct: 98.2,
  customers_active: 18,
  customers_total: 20,
  customers_at_risk: 2,
};

export const mockVehicles = [
  {
    id: "BUS-103",
    registration_plate: "KA-01-AB-1234",
    vehicle_type: "Heavy Haul Container Truck",
    revenue: 910000,
    operating_cost: 420000,
    contribution: 490000,
    margin_pct: 53.9,
    utilization_pct: 96.2,
    utilization_trend: 2.0,
    status: "Active",
    health_status: "Healthy", // Healthy | Warning | Loss
    next_service_days: 30,
    engine_hours: 4250,
    engine_life_pct: 42,
    fuel_efficiency_km: 52.4,
    cost_per_km: 24.2,
    assigned_routes: ["KOL-PUN-01", "DEL-MUM-04"],
    assigned_driver: "Ravi Kumar (D-023)",
    last_service_date: "2026-07-15",
    fuel_cost_monthly: 185000,
    maintenance_cost_monthly: 65000,
    driver_cost_monthly: 95000,
    allocation_cost_monthly: 75000
  },
  {
    id: "BUS-108",
    registration_plate: "MH-12-PQ-9876",
    vehicle_type: "Refrigerated Logistics Van",
    revenue: 840000,
    operating_cost: 410000,
    contribution: 430000,
    margin_pct: 51.2,
    utilization_pct: 94.8,
    utilization_trend: 1.5,
    status: "Active",
    health_status: "Healthy",
    next_service_days: 14,
    engine_hours: 3800,
    engine_life_pct: 38,
    fuel_efficiency_km: 49.8,
    cost_per_km: 26.1,
    assigned_routes: ["BLR-HYD-02"],
    assigned_driver: "Suresh Raina (D-041)",
    last_service_date: "2026-08-01",
    fuel_cost_monthly: 190000,
    maintenance_cost_monthly: 45000,
    driver_cost_monthly: 95000,
    allocation_cost_monthly: 80000
  },
  {
    id: "BUS-112",
    registration_plate: "TN-09-CD-4567",
    vehicle_type: "Multi-Axle Cargo Carrier",
    revenue: 780000,
    operating_cost: 450000,
    contribution: 330000,
    margin_pct: 42.3,
    utilization_pct: 91.5,
    utilization_trend: 0.8,
    status: "Active",
    health_status: "Healthy",
    next_service_days: 45,
    engine_hours: 5100,
    engine_life_pct: 51,
    fuel_efficiency_km: 46.2,
    cost_per_km: 28.5,
    assigned_routes: ["MAA-BLR-01"],
    assigned_driver: "Anil Deshmukh (D-019)",
    last_service_date: "2026-06-20",
    fuel_cost_monthly: 210000,
    maintenance_cost_monthly: 70000,
    driver_cost_monthly: 90000,
    allocation_cost_monthly: 80000
  },
  {
    id: "BUS-105",
    registration_plate: "DL-01-XY-3344",
    vehicle_type: "Express Parcel Truck",
    revenue: 650000,
    operating_cost: 545000,
    contribution: 105000,
    margin_pct: 16.2,
    utilization_pct: 78.4,
    utilization_trend: -2.1,
    status: "Active",
    health_status: "Warning",
    next_service_days: 7,
    engine_hours: 6800,
    engine_life_pct: 68,
    fuel_efficiency_km: 38.5,
    cost_per_km: 34.2,
    assigned_routes: ["DEL-JAI-03"],
    assigned_driver: "Vikram Singh (D-052)",
    last_service_date: "2026-07-02",
    fuel_cost_monthly: 260000,
    maintenance_cost_monthly: 110000,
    driver_cost_monthly: 85000,
    allocation_cost_monthly: 90000
  },
  {
    id: "BUS-102",
    registration_plate: "KA-01-CD-5678",
    vehicle_type: "Heavy Haul Container Truck",
    revenue: 724000,
    operating_cost: 716000,
    contribution: 8000,
    margin_pct: 1.1,
    utilization_pct: 62.1,
    utilization_trend: -5.0,
    status: "Active",
    health_status: "Loss",
    next_service_days: 2,
    engine_hours: 9200,
    engine_life_pct: 92,
    fuel_efficiency_km: 31.0,
    cost_per_km: 42.8,
    assigned_routes: ["KOL-ASN-01"],
    assigned_driver: "Priya Sharma (D-045)",
    last_service_date: "2026-05-10",
    fuel_cost_monthly: 340000,
    maintenance_cost_monthly: 196000,
    driver_cost_monthly: 90000,
    allocation_cost_monthly: 90000
  },
  {
    id: "BUS-104",
    registration_plate: "GJ-06-EF-9012",
    vehicle_type: "Medium Delivery Truck",
    revenue: 410000,
    operating_cost: 440000,
    contribution: -30000,
    margin_pct: -7.3,
    utilization_pct: 54.0,
    utilization_trend: -8.4,
    status: "Maintenance",
    health_status: "Loss",
    next_service_days: 0,
    engine_hours: 8900,
    engine_life_pct: 89,
    fuel_efficiency_km: 29.4,
    cost_per_km: 46.5,
    assigned_routes: ["AHM-SUR-02"],
    assigned_driver: "Unassigned",
    last_service_date: "2026-04-12",
    fuel_cost_monthly: 210000,
    maintenance_cost_monthly: 140000,
    driver_cost_monthly: 40000,
    allocation_cost_monthly: 50000
  }
];

export const mockRoutes = [
  {
    id: "R-101",
    route_code: "KOL-PUN-01",
    origin: "Kolkata Hub",
    destination: "Pune Terminal",
    customer_name: "TCS Logistics",
    revenue: 850000,
    cost: 212000,
    margin_pct: 75.0,
    trips_per_month: 180,
    utilization_pct: 95.0,
    assigned_vehicles: 4,
    assigned_driver: "Ravi Kumar",
    status: "Strong",
    health_status: "Healthy",
    sla_performance_pct: 99.1,
    cost_per_km: 18.2,
    revenue_per_km: 72.8,
    distance_km: 1850,
    exceptions_count: 1
  },
  {
    id: "R-102",
    route_code: "DEL-MUM-04",
    origin: "Delhi ICD",
    destination: "Mumbai Port",
    customer_name: "Reliance Retail",
    revenue: 1250000,
    cost: 420000,
    margin_pct: 66.4,
    trips_per_month: 240,
    utilization_pct: 92.4,
    assigned_vehicles: 6,
    assigned_driver: "Anil Deshmukh",
    status: "Strong",
    health_status: "Healthy",
    sla_performance_pct: 98.4,
    cost_per_km: 22.4,
    revenue_per_km: 66.8,
    distance_km: 1420,
    exceptions_count: 2
  },
  {
    id: "R-103",
    route_code: "BLR-HYD-02",
    origin: "Bengaluru East",
    destination: "Hyderabad Hub",
    customer_name: "Amazon Transportation",
    revenue: 680000,
    cost: 390000,
    margin_pct: 42.6,
    trips_per_month: 150,
    utilization_pct: 88.0,
    assigned_vehicles: 3,
    assigned_driver: "Suresh Raina",
    status: "Normal",
    health_status: "Healthy",
    sla_performance_pct: 96.5,
    cost_per_km: 24.1,
    revenue_per_km: 42.0,
    distance_km: 570,
    exceptions_count: 3
  },
  {
    id: "R-104",
    route_code: "MAA-BLR-01",
    origin: "Chennai Port",
    destination: "Bengaluru South",
    customer_name: "Tata Motors Cargo",
    revenue: 540000,
    cost: 440000,
    margin_pct: 18.5,
    trips_per_month: 110,
    utilization_pct: 74.2,
    assigned_vehicles: 2,
    assigned_driver: "Vikram Singh",
    status: "At Risk",
    health_status: "Warning",
    sla_performance_pct: 91.0,
    cost_per_km: 31.0,
    revenue_per_km: 38.0,
    distance_km: 350,
    exceptions_count: 5
  },
  {
    id: "R-105",
    route_code: "KOL-ASN-01",
    origin: "Kolkata South",
    destination: "Asansol Industrial Depot",
    customer_name: "PQR Ltd",
    revenue: 450000,
    cost: 390000,
    margin_pct: 13.2,
    trips_per_month: 90,
    utilization_pct: 48.0,
    assigned_vehicles: 2,
    assigned_driver: "Priya Sharma",
    status: "At Risk",
    health_status: "Loss",
    sla_performance_pct: 84.5,
    cost_per_km: 36.8,
    revenue_per_km: 42.4,
    distance_km: 210,
    exceptions_count: 8
  }
];

export const mockCustomers = [
  {
    id: "CUST-001",
    name: "Amazon Transportation",
    contract_id: "CTR-2024-889",
    revenue: 14500000, // YTD ₹1.45 Cr
    monthly_revenue: 1250000,
    direct_cost: 650000,
    allocated_cost: 210000,
    contribution: 390000,
    margin_pct: 31.2,
    sla_performance_pct: 99.2,
    renewal_days: 140,
    renewal_date: "2027-01-15",
    renewal_probability_pct: 94,
    status: "Key Accounts", // Q1: Key Accounts, Q2: Growth, Q3: Discontinue, Q4: Renegotiate
    health_status: "Healthy",
    quadrant: "Q1",
    pricing_recommendation: "Maintain terms & propose fleet expansion (+15% volume)",
    assigned_vehicles_count: 12,
    satisfaction_score: 4.9
  },
  {
    id: "CUST-002",
    name: "TCS Logistics",
    contract_id: "CTR-2025-104",
    revenue: 9800000,
    monthly_revenue: 850000,
    direct_cost: 310000,
    allocated_cost: 140000,
    contribution: 400000,
    margin_pct: 47.0,
    sla_performance_pct: 98.8,
    renewal_days: 210,
    renewal_date: "2027-03-22",
    renewal_probability_pct: 90,
    status: "Growth",
    health_status: "Healthy",
    quadrant: "Q2",
    pricing_recommendation: "High margin low revenue. Protect account and scale route capacity.",
    assigned_vehicles_count: 6,
    satisfaction_score: 4.8
  },
  {
    id: "CUST-003",
    name: "Reliance Retail",
    contract_id: "CTR-2024-512",
    revenue: 18200000,
    monthly_revenue: 1550000,
    direct_cost: 980000,
    allocated_cost: 340000,
    contribution: 230000,
    margin_pct: 14.8,
    sla_performance_pct: 96.5,
    renewal_days: 45,
    renewal_date: "2026-10-04",
    renewal_probability_pct: 75,
    status: "Renegotiate",
    health_status: "Warning",
    quadrant: "Q4",
    pricing_recommendation: "Increase contract rate by 12-15% or adjust fuel surcharge clause.",
    assigned_vehicles_count: 14,
    satisfaction_score: 4.2
  },
  {
    id: "CUST-004",
    name: "PQR Ltd",
    contract_id: "CTR-2023-901",
    revenue: 7200000,
    monthly_revenue: 600000,
    direct_cost: 410000,
    allocated_cost: 135000,
    contribution: 55000,
    margin_pct: 9.2,
    sla_performance_pct: 88.0,
    renewal_days: 30,
    renewal_date: "2026-09-20",
    renewal_probability_pct: 62,
    status: "Discontinue",
    health_status: "Loss",
    quadrant: "Q3",
    pricing_recommendation: "Contract renewal at risk. Reprice or reduce dedicated vehicle count.",
    assigned_vehicles_count: 5,
    satisfaction_score: 3.8
  }
];

export const mockDrivers = [
  {
    id: "D-023",
    name: "Ravi Kumar",
    assigned_vehicle: "BUS-103",
    assigned_route: "KOL-PUN-01",
    trips_this_month: 180,
    service_hours: 1440,
    attendance_pct: 98.0,
    cost_per_trip: 380,
    salary_monthly: 85000,
    productivity_score: 87,
    productivity_trend: 2.5,
    rank: 3,
    total_drivers: 45,
    status: "Active",
    health_status: "Healthy",
    incidents_count: 0,
    fuel_correlation_score: "8% above benchmark",
    feedback_score: 4.9
  },
  {
    id: "D-019",
    name: "Anil Deshmukh",
    assigned_vehicle: "BUS-112",
    assigned_route: "DEL-MUM-04",
    trips_this_month: 172,
    service_hours: 1380,
    attendance_pct: 96.5,
    cost_per_trip: 395,
    salary_monthly: 82000,
    productivity_score: 83,
    productivity_trend: 1.0,
    rank: 7,
    total_drivers: 45,
    status: "Active",
    health_status: "Healthy",
    incidents_count: 0,
    fuel_correlation_score: "5% above benchmark",
    feedback_score: 4.7
  },
  {
    id: "D-087",
    name: "Suresh Raina",
    assigned_vehicle: "BUS-108",
    assigned_route: "BLR-HYD-02",
    trips_this_month: 166,
    service_hours: 1328,
    attendance_pct: 94.0,
    cost_per_trip: 380,
    salary_monthly: 85000,
    productivity_score: 78,
    productivity_trend: -3.0,
    rank: 12,
    total_drivers: 45,
    status: "Active",
    health_status: "Healthy",
    incidents_count: 1,
    fuel_correlation_score: "Par with benchmark",
    feedback_score: 4.6
  },
  {
    id: "D-052",
    name: "Vikram Singh",
    assigned_vehicle: "BUS-105",
    assigned_route: "MAA-BLR-01",
    trips_this_month: 120,
    service_hours: 960,
    attendance_pct: 88.0,
    cost_per_trip: 445,
    salary_monthly: 78000,
    productivity_score: 69,
    productivity_trend: -1.5,
    rank: 28,
    total_drivers: 45,
    status: "Active",
    health_status: "Warning",
    incidents_count: 2,
    fuel_correlation_score: "4% below benchmark",
    feedback_score: 4.1
  },
  {
    id: "D-045",
    name: "Priya Sharma",
    assigned_vehicle: "BUS-102",
    assigned_route: "KOL-ASN-01",
    trips_this_month: 94,
    service_hours: 752,
    attendance_pct: 82.0,
    cost_per_trip: 520,
    salary_monthly: 75000,
    productivity_score: 64,
    productivity_trend: -5.0,
    rank: 39,
    total_drivers: 45,
    status: "Active",
    health_status: "Loss",
    incidents_count: 3,
    fuel_correlation_score: "12% below benchmark",
    feedback_score: 3.8
  }
];

export const mockInsights = [
  {
    id: "INS-001",
    type: "COST_ANOMALY",
    severity: "HIGH",
    entity_type: "Vehicle",
    entity_id: "BUS-102",
    headline: "Vehicle BUS-102 operating cost spiked +18% vs last month",
    metric_impact: "₹28,000 additional monthly cost",
    timestamp: "2 hours ago",
    recommendation: "Review fuel records & schedule engine diagnostics for BUS-102",
    action_type: "VIEW_VEHICLE",
    entity_ref: "BUS-102"
  },
  {
    id: "INS-002",
    type: "LOW_MARGIN_ROUTE",
    severity: "HIGH",
    entity_type: "Route",
    entity_id: "KOL-ASN-01",
    headline: "Route KOL-ASN-01 contribution margin dropped to 13.2%",
    metric_impact: "₹60,000 revenue at risk",
    timestamp: "5 hours ago",
    recommendation: "Renegotiate customer contract terms or consolidate off-peak trips",
    action_type: "VIEW_ROUTE",
    entity_ref: "KOL-ASN-01"
  },
  {
    id: "INS-003",
    type: "CUSTOMER_RISK",
    severity: "MEDIUM",
    entity_type: "Customer",
    entity_id: "CUST-004",
    headline: "PQR Ltd contract renewal in 30 days with 9.2% margin",
    metric_impact: "₹600,000 monthly revenue",
    timestamp: "1 day ago",
    recommendation: "Reprice contract terms (+12%) or reallocate dedicated vehicles",
    action_type: "VIEW_CUSTOMER",
    entity_ref: "CUST-004"
  },
  {
    id: "INS-004",
    type: "DRIVER_COST",
    severity: "MEDIUM",
    entity_type: "Driver",
    entity_id: "D-045",
    headline: "Driver D-045 cost per trip 18% above fleet average (₹520 vs ₹380)",
    metric_impact: "₹21,500 cost variance",
    timestamp: "1 day ago",
    recommendation: "Review route assignment or assign driver efficiency training",
    action_type: "VIEW_DRIVER",
    entity_ref: "D-045"
  },
  {
    id: "INS-005",
    type: "HIGH_PERFORMING",
    severity: "LOW",
    entity_type: "Vehicle",
    entity_id: "BUS-103",
    headline: "Vehicle BUS-103 achieved top margin performance (53.9%)",
    metric_impact: "₹490,000 monthly contribution",
    timestamp: "2 days ago",
    recommendation: "Benchmark route and driver maintenance practices across fleet",
    action_type: "VIEW_VEHICLE",
    entity_ref: "BUS-103"
  }
];

export const mockQuickBooksStatus = {
  connection_status: "Connected", // Connected | Disconnected | Pending
  company_name: "Fleet360 Logistics India Pvt Ltd",
  realm_id: "9130352948291048",
  last_sync_time: "2026-08-20 15:30 IST",
  sync_frequency: "Daily at 02:00 AM IST",
  synced_transactions_count: 1247,
  pending_mapping_count: 0,
  mapped_accounts: [
    { qb_account: "Fuel Expense (7010)", fleet_category: "Fuel Cost", status: "Mapped", count: 482 },
    { qb_account: "Vehicle Maintenance & Repairs (7020)", fleet_category: "Maintenance Cost", status: "Mapped", count: 215 },
    { qb_account: "Driver Wages & Salaries (6010)", fleet_category: "Driver Cost", status: "Mapped", count: 320 },
    { qb_account: "Fleet Insurance (6050)", fleet_category: "Operating Cost", status: "Mapped", count: 145 },
    { qb_account: "Depreciation - Transportation (7090)", fleet_category: "Allocation Overhead", status: "Mapped", count: 85 }
  ]
};
